
set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN K2 [get_ports clk_div108]
set_property PACKAGE_PIN P15 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk_div108]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

set_property PACKAGE_PIN J2 [get_ports clk_div104]
set_property IOSTANDARD LVCMOS33 [get_ports clk_div104]

set_property PACKAGE_PIN B2 [get_ports {sseg[0]}]
set_property PACKAGE_PIN B3 [get_ports {sseg[1]}]
set_property PACKAGE_PIN A1 [get_ports {sseg[2]}]
set_property PACKAGE_PIN B1 [get_ports {sseg[3]}]
set_property PACKAGE_PIN A3 [get_ports {sseg[4]}]
set_property PACKAGE_PIN A4 [get_ports {sseg[5]}]
set_property PACKAGE_PIN B4 [get_ports {sseg[6]}]
set_property PACKAGE_PIN D5 [get_ports {sseg[7]}]
set_property PACKAGE_PIN C1 [get_ports {an[2]}]
set_property PACKAGE_PIN G2 [get_ports {an[0]}]

set_property PACKAGE_PIN H1 [get_ports {an[3]}]
set_property PACKAGE_PIN C2 [get_ports {an[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {an1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg2[0]}]
set_property PACKAGE_PIN C2 [get_ports {an1[1]}]
set_property PACKAGE_PIN G2 [get_ports {an1[0]}]
set_property PACKAGE_PIN F1 [get_ports {an2[1]}]
set_property PACKAGE_PIN G1 [get_ports {an2[0]}]
set_property PACKAGE_PIN D5 [get_ports {sseg1[7]}]
set_property PACKAGE_PIN B4 [get_ports {sseg1[6]}]
set_property PACKAGE_PIN A4 [get_ports {sseg1[5]}]
set_property PACKAGE_PIN A3 [get_ports {sseg1[4]}]
set_property PACKAGE_PIN B1 [get_ports {sseg1[3]}]
set_property PACKAGE_PIN A1 [get_ports {sseg1[2]}]
set_property PACKAGE_PIN B3 [get_ports {sseg1[1]}]
set_property PACKAGE_PIN B2 [get_ports {sseg1[0]}]
set_property PACKAGE_PIN H2 [get_ports {sseg2[7]}]
set_property PACKAGE_PIN D4 [get_ports {sseg2[6]}]
set_property PACKAGE_PIN E3 [get_ports {sseg2[5]}]
set_property PACKAGE_PIN D3 [get_ports {sseg2[4]}]
set_property PACKAGE_PIN F4 [get_ports {sseg2[3]}]
set_property PACKAGE_PIN F3 [get_ports {sseg2[2]}]
set_property PACKAGE_PIN E2 [get_ports {sseg2[1]}]
set_property PACKAGE_PIN D2 [get_ports {sseg2[0]}]
set_property PACKAGE_PIN C1 [get_ports {an1[2]}]
set_property PACKAGE_PIN H1 [get_ports {an1[3]}]
set_property PACKAGE_PIN E1 [get_ports {an2[2]}]
set_property PACKAGE_PIN G6 [get_ports {an2[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
set_property PACKAGE_PIN P5 [get_ports {sw[7]}]
set_property PACKAGE_PIN P4 [get_ports {sw[6]}]
set_property PACKAGE_PIN P3 [get_ports {sw[5]}]
set_property PACKAGE_PIN P2 [get_ports {sw[4]}]
set_property PACKAGE_PIN R2 [get_ports {sw[3]}]
set_property PACKAGE_PIN M4 [get_ports {sw[2]}]
set_property PACKAGE_PIN N4 [get_ports {sw[1]}]
set_property PACKAGE_PIN R1 [get_ports {sw[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {sw_mode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_mode[0]}]
set_property PACKAGE_PIN T5 [get_ports sw_mode]

set_property IOSTANDARD LVCMOS33 [get_ports {DA_out[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_out[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DA_out[0]}]
set_property PACKAGE_PIN B17 [get_ports {DA_out[13]}]
set_property PACKAGE_PIN A15 [get_ports {DA_out[12]}]
set_property PACKAGE_PIN A16 [get_ports {DA_out[11]}]
set_property PACKAGE_PIN A13 [get_ports {DA_out[10]}]
set_property PACKAGE_PIN A14 [get_ports {DA_out[9]}]
set_property PACKAGE_PIN B18 [get_ports {DA_out[8]}]
set_property PACKAGE_PIN A18 [get_ports {DA_out[7]}]
set_property PACKAGE_PIN F13 [get_ports {DA_out[6]}]
set_property PACKAGE_PIN F14 [get_ports {DA_out[5]}]
set_property PACKAGE_PIN B13 [get_ports {DA_out[4]}]
set_property PACKAGE_PIN B14 [get_ports {DA_out[3]}]
set_property PACKAGE_PIN D14 [get_ports {DA_out[2]}]
set_property PACKAGE_PIN C14 [get_ports {DA_out[1]}]
set_property PACKAGE_PIN B11 [get_ports {DA_out[0]}]

set_property PACKAGE_PIN B16 [get_ports DA_clk]
set_property IOSTANDARD LVCMOS33 [get_ports DA_clk]

set_property IOSTANDARD LVCMOS33 [get_ports {AD_in[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_in[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {AD_in[0]}]
set_property PACKAGE_PIN H16 [get_ports {AD_in[0]}]
set_property PACKAGE_PIN F16 [get_ports {AD_in[1]}]
set_property PACKAGE_PIN F15 [get_ports {AD_in[2]}]
set_property PACKAGE_PIN G14 [get_ports {AD_in[3]}]
set_property PACKAGE_PIN H14 [get_ports {AD_in[4]}]
set_property PACKAGE_PIN D17 [get_ports {AD_in[5]}]
set_property PACKAGE_PIN E17 [get_ports {AD_in[6]}]
set_property PACKAGE_PIN J13 [get_ports {AD_in[7]}]
set_property PACKAGE_PIN K13 [get_ports {AD_in[8]}]
set_property PACKAGE_PIN G17 [get_ports {AD_in[9]}]
set_property PACKAGE_PIN H17 [get_ports AD_clk]
set_property IOSTANDARD LVCMOS33 [get_ports AD_clk]


#set_property PACKAGE_PIN D17 [get_ports {AD_in[5]}]
#set_property PACKAGE_PIN E17 [get_ports {AD_in[6]}]
#set_property PACKAGE_PIN J13 [get_ports {AD_in[7]}]
#set_property PACKAGE_PIN K13 [get_ports {AD_in[8]}]
#set_property PACKAGE_PIN G17 [get_ports {AD_in[9]}]

set_property PACKAGE_PIN T3 [get_ports {sw_mode[1]}]
set_property PACKAGE_PIN T5 [get_ports {sw_mode[0]}]

set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports bt_pw_on]
set_property -dict {PACKAGE_PIN C16 IOSTANDARD LVCMOS33} [get_ports bt_master_slave]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports bt_sw_hw]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVCMOS33} [get_ports bt_rst_n]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33} [get_ports bt_sw]
set_property PACKAGE_PIN L3 [get_ports rxd_pin]
set_property IOSTANDARD LVCMOS33 [get_ports rxd_pin]
#Bank = 16, Pin name = ,					Sch name = UART_RXD_OUT
set_property PACKAGE_PIN N2 [get_ports txd_pin]
set_property IOSTANDARD LVCMOS33 [get_ports txd_pin]

set_property IOSTANDARD LVCMOS33 [get_ports btn]
set_property IOSTANDARD LVCMOS33 [get_ports dds_led]
set_property PACKAGE_PIN K1 [get_ports dds_led]
set_property PACKAGE_PIN U3 [get_ports btn]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets btn]


set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports pwm_dip]
set_property PACKAGE_PIN U2 [get_ports pwm_dip]
set_property PACKAGE_PIN F6 [get_ports {led[14]}]
set_property PACKAGE_PIN G4 [get_ports {led[13]}]
set_property PACKAGE_PIN G3 [get_ports {led[12]}]
set_property PACKAGE_PIN J4 [get_ports {led[11]}]
set_property PACKAGE_PIN H4 [get_ports {led[10]}]
set_property PACKAGE_PIN J3 [get_ports {led[9]}]
set_property PACKAGE_PIN J2 [get_ports {led[8]}]
set_property PACKAGE_PIN K2 [get_ports {led[7]}]
set_property PACKAGE_PIN H6 [get_ports {led[6]}]
set_property PACKAGE_PIN H5 [get_ports {led[5]}]
set_property PACKAGE_PIN J5 [get_ports {led[4]}]
set_property PACKAGE_PIN K6 [get_ports {led[3]}]
set_property PACKAGE_PIN L1 [get_ports {led[2]}]
set_property PACKAGE_PIN M1 [get_ports {led[1]}]
set_property PACKAGE_PIN K3 [get_ports {led[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports AM_dip]
set_property PACKAGE_PIN R3 [get_ports AM_dip]
set_property IOSTANDARD LVCMOS33 [get_ports dds_dip]
set_property PACKAGE_PIN U3 [get_ports dds_dip]
